import {
  User,
  Channel,
  Server,
  FriendApplication,
  MemberApplication,
  ServerMember,
  Permission,
  UserMember,
  Member,
  Friend,
  UserFriend,
  FriendGroup,
} from '@/types';

export const createDefault = {
  user: (overrides: Partial<User> = {}): User => ({
    id: '',
    name: '',
    avatar: `${Date.now()}`,
    avatarUrl: `${process.env.NEXT_PUBLIC_SERVER_URL}/images/userAvatars/`,
    signature: '',
    status: 'online',
    gender: 'Male',
    birthYear: new Date().getFullYear() - 20,
    birthMonth: 1,
    birthDay: 1,
    country: 'taiwan',
    level: 0,
    vip: 0,
    xp: 0,
    requiredXp: 0,
    progress: 0,
    currentChannelId: '',
    currentServerId: '',
    lastActiveAt: 0,
    createdAt: 0,
    ...overrides,
  }),

  channel: (overrides: Partial<Channel> = {}): Channel => ({
    id: '',
    name: '',
    type: 'channel',
    visibility: 'public',
    password: '',
    voiceMode: 'free',
    isLobby: false,
    isRoot: false,
    slowmode: false,
    forbidText: false,
    forbidGuestText: false,
    forbidGuestUrl: false,
    guestTextMaxLength: 2000,
    guestTextWaitTime: 0,
    guestTextGapTime: 0,
    bitrate: 64000,
    userLimit: 0,
    order: 0,
    serverId: '',
    categoryId: '',
    createdAt: 0,
    ...overrides,
  }),

  server: (overrides: Partial<Server> = {}): Server => ({
    id: '',
    name: '',
    avatar: `${Date.now()}`,
    avatarUrl: `${process.env.NEXT_PUBLIC_SERVER_URL}/images/serverAvatars/`,
    announcement: '',
    description: '',
    slogan: '',
    type: 'other',
    visibility: 'public',
    allowDirectMessage: true,
    level: 0,
    wealth: 0,
    displayId: '',
    lobbyId: '',
    ownerId: '',
    createdAt: 0,
    receiveApply: true,
    applyNotice: '',
    ...overrides,
  }),

  friend: (overrides: Partial<Friend> = {}): Friend => ({
    id: '',
    isBlocked: false,
    friendGroupId: '',
    userId: '',
    targetId: '',
    createdAt: 0,
    ...overrides,
  }),

  friendGroup: (overrides: Partial<FriendGroup> = {}): FriendGroup => ({
    id: '',
    name: '',
    order: 0,
    userId: '',
    createdAt: 0,
    ...overrides,
  }),

  userFriend: (overrides: Partial<UserFriend> = {}): UserFriend => ({
    ...createDefault.friend(),
    ...createDefault.user(),
    ...overrides,
  }),

  member: (overrides: Partial<Member> = {}): Member => ({
    id: '',
    isBlocked: false,
    nickname: null,
    contribution: 0,
    lastMessageTime: 0,
    lastJoinChannelTime: 0,
    permissionLevel: Permission.Guest,
    userId: '',
    serverId: '',
    createdAt: 0,
    ...overrides,
  }),

  userMember: (overrides: Partial<UserMember> = {}): UserMember => ({
    ...createDefault.member(),
    ...createDefault.server(),
    ...overrides,
  }),

  serverMember: (overrides: Partial<ServerMember> = {}): ServerMember => ({
    ...createDefault.member(),
    ...createDefault.user(),
    ...overrides,
  }),

  friendApplication: (
    overrides: Partial<FriendApplication> = {},
  ): FriendApplication => ({
    description: '',
    applicationStatus: 'pending',
    senderId: '',
    receiverId: '',
    ...createDefault.user(),
    ...overrides,
  }),

  memberApplication: (
    overrides: Partial<MemberApplication> = {},
  ): MemberApplication => ({
    description: '',
    applicationStatus: 'pending',
    userId: '',
    serverId: '',
    ...createDefault.user(),
    ...overrides,
  }),
};
